name: project
description: "A smart calculator with advanced features built using Flutter."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # === STATE MANAGEMENT ===
  flutter_riverpod: ^2.5.1

  # === PENYIMPANAN LOKAL (RIWAYAT & PENGATURAN) ===
  shared_preferences: ^2.2.2

  # === LOGIKA MATEMATIKA (PARSING EKSPRESI) ===
  math_expressions: ^2.4.0

  # === FORMAT ANGKA, TANGGAL, MATA UANG ===
  intl: ^0.19.0
  speech_to_text: 7.3.0
  flutter_native_splash: ^2.4.1

  # === OPSIONAL: TAMBAHKAN NANTI SAAT BUTUH ===
  # http: ^1.2.0
  # flutter_dotenv: ^5.1.0
  # vibration: ^1.8.4
  # flutter_svg: ^2.0.7
  # lottie: ^3.1.0
  # url_launcher: ^6.2.5
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/CALC.png
    - assets/CALC.png
flutter_native_splash:
  color: "#2196F3"
  color_dark: "#0D47A1"
  image: assets/CL.png
  android_12:
    color: "#2196F3"
  ios: true
  android: true